# Generated by Django 5.1.1 on 2025-01-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='ordonnance',
            field=models.FileField(blank=True, null=True, upload_to='ordonnances/'),
        ),
    ]
