# Generated by Django 4.2.18 on 2025-01-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='url_image',
            field=models.ImageField(blank=True, null=True, upload_to='produits/'),
        ),
    ]
