# Generated by Django 5.1.1 on 2025-01-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharma', '0002_commande_ordonnance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='url_image',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
