# Generated by Django 5.1.5 on 2025-02-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharma', '0005_alter_commande_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='mode_livraison',
            field=models.CharField(choices=[('standard', 'Livraison standard (2h à 4h) : 3000f'), ('express', 'Livraison express (≤1h) : 5000f'), ('retrait', 'Retrait en magasin')], default='standard', max_length=20),
        ),
    ]
